version: '3'
services:
  gitlab-ce:
    restart: always
    image: registry.cn-qingdao.aliyuncs.com/wod/sameersbn-gitlab:11.4.5
    ports:
      - 443:443
      - 80:80
      - 22:22
    volumes:
      - /root/gitlab/config:/etc/gitlab
      - /root/gitlab/logs:/var/log/gitlab
      - /root/data:/var/opt/gitlab
