###############################################################################
## prod 生产环境
###############################################################################
## 数据库设置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: KCE17cHefBHz8Uf/KI7t67KNd+H6JdC+wflLMYgD7meejUTTIOJWYCtGFxvEA42IMPFd+zKKgZ4FvVJZJVE8lw==
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIv8AxODdgy3Fz4KY3BzdHOfLexBXoNQxik4W6LE4oOXAfWsmOkuvRDHzvbIXd3HIbFK1kyKGnu/QSzqouGmGgMCAwEAAQ==
    initialSize: 1
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    validationQuery: SELECT 1
    filters: stat,log4j,wall,config
###############################################################################
## redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 10000ms
    jedis:
      pool:
        max-active: 50
        max-idle: 5
        min-idle: 0
        max-wait: 10000ms
###############################################################################
## 日志配置路径
logging:
  config: classpath:log4j2-dev.xml
###############################################################################
## swagger配置
swagger:
  enable: false
###############################################################################
