version: '3'
services:
  rabbitmq:
    restart: always
    image: rabbitmq:3.7.8-management
    ports:
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 25672:25672
    volumes:
      - /root/data/rabbitmq-data/:/var/rabbitmq/lib


