version: '3.1'

services:

  db1:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /root/mysql/db1/data:/var/lib/mysql
      - /root/mysql/db1/logs:/logs
      - /root/mysql/db1/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root@123456
#      MYSQL_USER: 'mysql'
#      MYSQL_PASS: 'mysql'

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

  db2:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    volumes:
      - /root/mysql/db2/data:/var/lib/mysql
      - /root/mysql/db2/logs:/logs
      - /root/mysql/db2/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root@123456

  db3:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    volumes:
      - /root/mysql/db3/data:/var/lib/mysql
      - /root/mysql/db3/logs:/logs
      - /root/mysql/db3/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root@123456